### ISSUE TITLE
How to set ColResize full width?

### ISSUE THREAD

**Issue by yurenlimbu** [smasala/ColResize#17]
Hi, 
Thanks for a great plugin. I'm unable to set 100% width on the table here is the issue https://codepen.io/yurenlimbu/pen/YgwemY. I want to create full width as parent div. How can I set this?

**Comment by smasala** [comment]
@yurenlimbu the codepen link has a table with `width 100%` and the table is showing as filling the entire width of the window. What is the exact issue?

**Comment by smasala** [comment]
Inactivity
