### ISSUE TITLE
How to create with tabs?

### ISSUE THREAD

**Issue by yurenlimbu** [smasala/ColResize#18]
Hi,
Thanks for a great plugin.

I'm trying to create ColResize with tabs but only working on the first active tab. Here is the example https://codepen.io/yurenlimbu/pen/PMwzEy?editors=1010.

**Comment by smasala** [comment]
@yurenlimbu I assume it's because the content has not rendered correctly and the widths cannot be calculated. You'll need to trigger the intances on tab switch.
