### ISSUE TITLE
does not work with boostrap styling

### ISSUE THREAD

**Issue by mafar** [smasala/ColResize#2]
See here.
https://jsfiddle.net/bababalcksheep/ftmsp3rg/

It will be helpfulll if all datatables plugins and styles are supported and shown in demo as well

**Comment by smasala** [comment]
The `<tfoot>` tag is causing the prob here. Not bootstrap.

Added issue for this: https://github.com/smasala/ColResize/issues/3

**Comment by mafar** [comment]
I fixed fiddle again as you suggested. https://jsfiddle.net/bababalcksheep/ftmsp3rg/9/

1. Now try resizing any column.
1. press ctrl + mouse scroll up to zoom in page. 
1. Vertical scroll bar is in middle of table

**Comment by smasala** [comment]
@mafar yes, page zoom causes weird side-effects. https://github.com/smasala/ColResize/issues/4

Feel free to attempt a few PR's if you like 👍
