### ISSUE TITLE
Unable to Click on table rows if colResize.scrollY is used

### ISSUE THREAD

**Issue by TanmaySM** [smasala/ColResize#5]
Using scrollY option in the plugin prevents clicking on actual table.

**Comment by smasala** [comment]
Have you configuration it correctly?
https://github.com/smasala/ColResize/blob/master/Readme.md#configuration--options

 If you have... a running demo with jsfiddle or similar would be helpful. Thanks

**Comment by TanmayMule** [comment]
Thanks for your replay. I have checked my configuration and it correct as per your ReadMe.
I have created JsFiddle here [https://jsfiddle.net/Tanmay93/b8qp8jxq/](https://jsfiddle.net/Tanmay93/b8qp8jxq/)

Thanks.

**Comment by smasala** [comment]
Thanks, I'll put out a minor fix in a mo

**Comment by smasala** [comment]
v2.5.3 fixes this issue in latest Chrome, FF and Edge versions.

**Comment by TanmayMule** [comment]
Sorry but this fix does not work fir me...
Please remove this fix asap....as it is disabling pointer events on scroll
bar as well.....

**Comment by smasala** [comment]
v2.5.4 fixes both issues. v2.5.3 removed. Please reopen if need be.
