### ISSUE TITLE
Please add option to disable real-time drag (live drag). 

### ISSUE THREAD

**Issue by TanmaySM** [smasala/ColResize#6]
Enhancement Request
-------------------------
Please add option to disable real-time drag (live drag). Because it is performing slower specially when dealing with huge or extremely complicated tables. 

I have created jsFiddle of other third party jQuery plugin which is having same feature.
http://jsfiddle.net/eLm6ugp7/183/

Thanks,
Tanmay

**Comment by smasala** [comment]
This is not something that is done quickly, maybe you would like to create a pull request or reduce the table size by adding pagination or other features such as defer loading
