### ISSUE TITLE
Add ability to save column sizes

### ISSUE THREAD

**Issue by PatrickHarriss** [smasala/ColResize#8]
When using the stateSave Datatables functionality would like the column sizes saved so when the user expands or shrinks the column size it will remember those settings the next time the table is initialized.

**Comment by konuch** [comment]
This feature would be really appreciated.

**Comment by smasala** [comment]
@PatrickHarriss I don't think there will be plans to alter the default save state mechanism to accommodate the plugin. A possibility would be to get and save the widths of the columns on `stateSaveCallback` in a separate object and read and set the widths during `stateLoadCallback` again.

**Comment by PatrickHarriss** [comment]
Thanks for looking at this, and thanks for the plugin. I'll look into the suggestions you gave. I was going to mention that the ColReorder plugin saves the state of the column order but realized that is an extension and not a plugin so might not be apples to apples.

**Comment by smasala** [comment]
Solved with latest release [v2.6.0](https://github.com/smasala/ColResize/releases/tag/v2.6.0)

**Comment by smasala** [comment]
@PatrickHarriss @konuch did the latest release solve the issue?

**Comment by PatrickHarriss** [comment]
It did. Thank you.
